code_syntax_highlight = "onedark-pro"

file_panel_border = "#5c6370"
sidebar_border = "#5c6370"
footer_border = "#5c6370"

file_panel_border_active = "#61afef"
sidebar_border_active = "#e06c75"
footer_border_active = "#98c379"
modal_border_active = "#56b6c2"

full_screen_bg = "#282c34"
file_panel_bg = "#282c34"
sidebar_bg = "#282c34"
footer_bg = "#282c34"
modal_bg = "#3b4048"

full_screen_fg = "#abb2bf"
file_panel_fg = "#abb2bf"
sidebar_fg = "#abb2bf"
footer_fg = "#abb2bf"
modal_fg = "#abb2bf"

cursor = "#61afef"
correct = "#98c379"
error = "#e06c75"
hint = "#61afef"
cancel = "#d19a66"
gradient_color = ["#61afef", "#c678dd"]

file_panel_top_directory_icon = "#d19a66"
file_panel_top_path = "#d19a66"
file_panel_item_selected_fg = "#56b6c2"
file_panel_item_selected_bg = "#282c34"

sidebar_title = "#61afef"
sidebar_item_selected_fg = "#56b6c2"
sidebar_item_selected_bg = "#282c34"
sidebar_divider = "#5c6370"

modal_cancel_fg = "#ffffff"
modal_cancel_bg = "#e06c75"

modal_confirm_fg = "#ffffff"
modal_confirm_bg = "#56b6c2"

help_menu_hotkey = "#56b6c2"
help_menu_title = "#c678dd"
