-- Highlights for the plugins actually installed in this config
-- (see lazy-lock.json). Sidebars, pickers and popups sit on the panel/float
-- surfaces so they read as VS Code's side bar and widgets rather than editor.

---@param p table palette
---@return table<string, vim.api.keyset.highlight>
return function(p)
  return {
    -- gitsigns --------------------------------------------------------------
    GitSignsAdd = { fg = p.gutter_add }, -- editorGutter.addedBackground
    GitSignsChange = { fg = p.gutter_change }, -- editorGutter.modifiedBackground
    GitSignsDelete = { fg = p.gutter_delete }, -- editorGutter.deletedBackground
    GitSignsTopdelete = { fg = p.gutter_delete },
    GitSignsChangedelete = { fg = p.gutter_change },
    GitSignsUntracked = { fg = p.git_add },
    GitSignsAddLn = { bg = p.diff_add },
    GitSignsChangeLn = { bg = p.diff_change },
    GitSignsDeleteLn = { bg = p.diff_delete },
    GitSignsAddInline = { bg = p.diff_text_add },
    GitSignsChangeInline = { bg = p.diff_text_add },
    GitSignsDeleteInline = { bg = p.diff_text_del },
    GitSignsCurrentLineBlame = { fg = "#969696" }, -- git.blame.editorDecorationForeground

    -- neo-tree --------------------------------------------------------------
    NeoTreeNormal = { fg = p.fg_ui, bg = p.bg_panel },
    NeoTreeNormalNC = { fg = p.fg_ui, bg = p.bg_panel },
    NeoTreeWinSeparator = { fg = p.border, bg = p.bg_panel },
    NeoTreeEndOfBuffer = { fg = p.bg_panel, bg = p.bg_panel },
    NeoTreeRootName = { fg = p.fg_ui, bold = true },
    NeoTreeTitleBar = { fg = p.on_accent, bg = p.accent_badge },
    NeoTreeDirectoryName = { fg = p.fg_ui },
    NeoTreeDirectoryIcon = { fg = p.fg_dim },
    NeoTreeFileName = { fg = p.fg_ui },
    NeoTreeFileIcon = { fg = p.fg_dim },
    NeoTreeFileNameOpened = { fg = p.fg_ui },
    NeoTreeIndentMarker = { fg = p.fg_gutter },
    NeoTreeExpander = { fg = p.fg_dim },
    NeoTreeCursorLine = { bg = p.bg_sel_list },
    NeoTreeDimText = { fg = p.fg_disabled },
    NeoTreeSymbolicLinkTarget = { fg = p.link },
    NeoTreeGitAdded = { fg = p.git_add },
    NeoTreeGitModified = { fg = p.git_change },
    NeoTreeGitDeleted = { fg = p.git_delete },
    NeoTreeGitConflict = { fg = p.error },
    NeoTreeGitUntracked = { fg = p.git_add },
    NeoTreeGitIgnored = { fg = p.git_ignored },
    NeoTreeGitStaged = { fg = p.git_add },
    NeoTreeGitUnstaged = { fg = p.git_change },
    NeoTreeFloatBorder = { fg = p.border, bg = p.bg_float },
    NeoTreeFloatTitle = { fg = p.fg_ui, bg = p.bg_float },
    NeoTreeTabActive = { fg = p.fg_ui, bg = p.bg_panel, bold = true },
    NeoTreeTabInactive = { fg = p.fg_disabled, bg = p.bg_panel },
    NeoTreeTabSeparatorActive = { fg = p.accent, bg = p.bg_panel },
    NeoTreeTabSeparatorInactive = { fg = p.border, bg = p.bg_panel },

    -- snacks ----------------------------------------------------------------
    SnacksNormal = { fg = p.fg_ui, bg = p.bg_float },
    SnacksNormalNC = { fg = p.fg_ui, bg = p.bg_float },
    SnacksWinBar = { fg = p.fg_ui, bg = p.bg_float, bold = true },
    SnacksWinBarNC = { fg = p.fg_dim, bg = p.bg_float },
    SnacksBackdrop = { bg = "#000000" },
    SnacksIndent = { fg = p.indent }, -- editorIndentGuide.background1
    SnacksIndentScope = { fg = p.fg_gutter }, -- ...activeBackground1
    SnacksIndentChunk = { fg = p.fg_gutter },
    SnacksIndentBlank = { fg = p.indent },
    SnacksNotifierInfo = { fg = p.info, bg = p.bg_float },
    SnacksNotifierWarn = { fg = p.warn, bg = p.bg_float },
    SnacksNotifierError = { fg = p.error, bg = p.bg_float },
    SnacksNotifierDebug = { fg = p.fg_dim, bg = p.bg_float },
    SnacksNotifierTrace = { fg = p.purple, bg = p.bg_float },
    SnacksNotifierBorderInfo = { fg = p.info, bg = p.bg_float },
    SnacksNotifierBorderWarn = { fg = p.warn, bg = p.bg_float },
    SnacksNotifierBorderError = { fg = p.error, bg = p.bg_float },
    SnacksNotifierTitleInfo = { fg = p.info, bg = p.bg_float },
    SnacksNotifierTitleWarn = { fg = p.warn, bg = p.bg_float },
    SnacksNotifierTitleError = { fg = p.error, bg = p.bg_float },
    SnacksDashboardHeader = { fg = p.accent },
    SnacksDashboardIcon = { fg = p.func },
    SnacksDashboardDesc = { fg = p.fg_ui },
    SnacksDashboardKey = { fg = p.type },
    SnacksDashboardFooter = { fg = p.fg_dim },
    SnacksDashboardTitle = { fg = p.link },
    SnacksDashboardDir = { fg = p.fg_dim },
    SnacksDashboardSpecial = { fg = p.func },
    -- picker
    SnacksPicker = { fg = p.fg_ui, bg = p.bg_float },
    SnacksPickerBorder = { fg = p.border, bg = p.bg_float },
    SnacksPickerTitle = { fg = p.fg_ui, bg = p.bg_float, bold = true },
    SnacksPickerInput = { fg = p.fg_ui, bg = p.bg_float },
    SnacksPickerInputBorder = { fg = p.accent, bg = p.bg_float },
    SnacksPickerInputSearch = { fg = p.type },
    SnacksPickerList = { fg = p.fg_ui, bg = p.bg_float },
    SnacksPickerListCursorLine = { bg = p.bg_sel_menu },
    SnacksPickerPreview = { fg = p.fg, bg = p.bg },
    SnacksPickerPreviewBorder = { fg = p.border, bg = p.bg },
    SnacksPickerPreviewTitle = { fg = p.fg_ui, bg = p.bg, bold = true },
    SnacksPickerMatch = { fg = p.link, bold = true }, -- list.highlightForeground
    SnacksPickerDir = { fg = p.fg_dim },
    SnacksPickerFile = { fg = p.fg_ui },
    SnacksPickerIdx = { fg = p.fg_disabled },
    SnacksPickerRow = { fg = p.fg_dim },
    SnacksPickerCol = { fg = p.fg_disabled },
    SnacksPickerSelected = { fg = p.type },
    SnacksPickerPrompt = { fg = p.accent },
    SnacksPickerGitStatusAdded = { fg = p.git_add },
    SnacksPickerGitStatusModified = { fg = p.git_change },
    SnacksPickerGitStatusDeleted = { fg = p.git_delete },
    SnacksPickerGitStatusUntracked = { fg = p.git_add },
    SnacksPickerGitStatusIgnored = { fg = p.git_ignored },

    -- bufferline ------------------------------------------------------------
    BufferLineFill = { bg = p.bg_panel }, -- editorGroupHeader.tabsBackground
    BufferLineBackground = { fg = p.fg_dim, bg = p.bg_panel },
    BufferLineBufferVisible = { fg = p.fg_dim, bg = p.bg_panel },
    BufferLineBufferSelected = { fg = p.fg_ui, bg = p.bg, bold = true },
    BufferLineIndicatorSelected = { fg = p.accent, bg = p.bg }, -- tab.activeBorderTop
    BufferLineIndicatorVisible = { fg = p.bg_panel, bg = p.bg_panel },
    BufferLineSeparator = { fg = p.border, bg = p.bg_panel },
    BufferLineSeparatorSelected = { fg = p.border, bg = p.bg },
    BufferLineSeparatorVisible = { fg = p.border, bg = p.bg_panel },
    BufferLineCloseButton = { fg = p.fg_dim, bg = p.bg_panel },
    BufferLineCloseButtonVisible = { fg = p.fg_dim, bg = p.bg_panel },
    BufferLineCloseButtonSelected = { fg = p.fg_ui, bg = p.bg },
    BufferLineModified = { fg = p.git_change, bg = p.bg_panel },
    BufferLineModifiedVisible = { fg = p.git_change, bg = p.bg_panel },
    BufferLineModifiedSelected = { fg = p.git_change, bg = p.bg },
    BufferLineError = { fg = p.error, bg = p.bg_panel },
    BufferLineErrorSelected = { fg = p.error, bg = p.bg },
    BufferLineWarning = { fg = p.warn, bg = p.bg_panel },
    BufferLineWarningSelected = { fg = p.warn, bg = p.bg },
    BufferLineInfo = { fg = p.info, bg = p.bg_panel },
    BufferLineInfoSelected = { fg = p.info, bg = p.bg },
    BufferLineHint = { fg = p.hint, bg = p.bg_panel },
    BufferLineHintSelected = { fg = p.hint, bg = p.bg },
    BufferLineDuplicate = { fg = p.fg_disabled, bg = p.bg_panel },
    BufferLineDuplicateSelected = { fg = p.fg_dim, bg = p.bg },
    BufferLineOffsetSeparator = { fg = p.border, bg = p.bg_panel },

    -- noice -----------------------------------------------------------------
    NoiceCmdline = { fg = p.fg_ui, bg = p.bg_float },
    NoiceCmdlineIcon = { fg = p.accent },
    NoiceCmdlineIconSearch = { fg = p.git_change },
    NoiceCmdlinePopup = { fg = p.fg_ui, bg = p.bg_float },
    NoiceCmdlinePopupBorder = { fg = p.border, bg = p.bg_float },
    NoiceCmdlinePopupBorderSearch = { fg = p.git_change, bg = p.bg_float },
    NoiceCmdlinePopupTitle = { fg = p.fg_ui, bg = p.bg_float },
    NoiceConfirm = { fg = p.fg_ui, bg = p.bg_float },
    NoiceConfirmBorder = { fg = p.border, bg = p.bg_float },
    NoicePopup = { fg = p.fg_ui, bg = p.bg_float },
    NoicePopupBorder = { fg = p.border, bg = p.bg_float },
    NoiceMini = { fg = p.fg_ui, bg = p.bg_float },
    NoiceVirtualtext = { fg = p.fg_dim },
    NoiceLspProgressTitle = { fg = p.fg_ui },
    NoiceLspProgressClient = { fg = p.link },
    NoiceLspProgressSpinner = { fg = p.accent },

    -- which-key -------------------------------------------------------------
    WhichKey = { fg = p.type },
    WhichKeyGroup = { fg = p.link },
    WhichKeyDesc = { fg = p.fg_ui },
    WhichKeySeparator = { fg = p.fg_disabled },
    WhichKeyFloat = { bg = p.bg_float },
    WhichKeyBorder = { fg = p.border, bg = p.bg_float },
    WhichKeyTitle = { fg = p.fg_ui, bg = p.bg_float },
    WhichKeyValue = { fg = p.fg_dim },
    WhichKeyIcon = { fg = p.constant },
    WhichKeyIconAzure = { fg = p.blue },
    WhichKeyIconBlue = { fg = p.blue },
    WhichKeyIconCyan = { fg = p.link },
    WhichKeyIconGreen = { fg = p.green },
    WhichKeyIconGrey = { fg = p.fg_dim },
    WhichKeyIconOrange = { fg = p.orange },
    WhichKeyIconPurple = { fg = p.purple },
    WhichKeyIconRed = { fg = p.red },
    WhichKeyIconYellow = { fg = p.yellow },
    WhichKeyNormal = { bg = p.bg_float },

    -- trouble ---------------------------------------------------------------
    TroubleNormal = { fg = p.fg_ui, bg = p.bg_panel },
    TroubleNormalNC = { fg = p.fg_ui, bg = p.bg_panel },
    TroubleText = { fg = p.fg_ui },
    TroubleCount = { fg = p.on_accent, bg = p.accent_badge }, -- badge.*
    TroubleIndent = { fg = p.fg_gutter },
    TroubleIndentFoldClosed = { fg = p.fg_dim },
    TroubleFilename = { fg = p.fg_ui },
    TroubleDirectory = { fg = p.fg_dim },
    TroublePos = { fg = p.fg_disabled },
    TroubleIconDirectory = { fg = p.fg_dim },
    TroubleSource = { fg = p.fg_dim },
    TroubleCode = { fg = p.fg_disabled },

    -- flash -----------------------------------------------------------------
    FlashBackdrop = { fg = p.fg_disabled },
    FlashLabel = { fg = p.on_accent, bg = p.error, bold = true },
    FlashMatch = { bg = p.bg_search },
    FlashCurrent = { bg = p.bg_search_cur },
    FlashPrompt = { fg = p.fg_ui, bg = p.bg_float },
    FlashPromptIcon = { fg = p.accent },

    -- todo-comments ---------------------------------------------------------
    TodoBgFIX = { fg = p.bg, bg = p.error, bold = true },
    TodoBgTODO = { fg = p.bg, bg = p.info, bold = true },
    TodoBgHACK = { fg = p.bg, bg = p.warn, bold = true },
    TodoBgWARN = { fg = p.bg, bg = p.warn, bold = true },
    TodoBgPERF = { fg = p.bg, bg = p.purple, bold = true },
    TodoBgNOTE = { fg = p.bg, bg = p.hint, bold = true },
    TodoBgTEST = { fg = p.bg, bg = p.purple, bold = true },
    TodoFgFIX = { fg = p.error },
    TodoFgTODO = { fg = p.info },
    TodoFgHACK = { fg = p.warn },
    TodoFgWARN = { fg = p.warn },
    TodoFgPERF = { fg = p.purple },
    TodoFgNOTE = { fg = p.hint },
    TodoFgTEST = { fg = p.purple },
    TodoSignFIX = { fg = p.error },
    TodoSignTODO = { fg = p.info },
    TodoSignHACK = { fg = p.warn },
    TodoSignWARN = { fg = p.warn },
    TodoSignPERF = { fg = p.purple },
    TodoSignNOTE = { fg = p.hint },
    TodoSignTEST = { fg = p.purple },

    -- blink.cmp -------------------------------------------------------------
    BlinkCmpMenu = { fg = p.fg_ui, bg = p.bg_float },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_float },
    BlinkCmpMenuSelection = { bg = p.bg_sel_menu },
    BlinkCmpScrollBarThumb = { bg = p.fg_disabled },
    BlinkCmpScrollBarGutter = { bg = p.bg_float },
    BlinkCmpLabel = { fg = p.fg_ui, bg = p.bg_float },
    BlinkCmpLabelDeprecated = { fg = p.fg_disabled, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.link, bold = true },
    BlinkCmpLabelDetail = { fg = p.fg_dim },
    BlinkCmpLabelDescription = { fg = p.fg_dim },
    BlinkCmpKind = { fg = p.constant },
    BlinkCmpSource = { fg = p.fg_disabled },
    BlinkCmpGhostText = { fg = p.fg_disabled }, -- editorGhostText.foreground
    BlinkCmpDoc = { fg = p.fg_ui, bg = p.bg_float },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg_float },
    BlinkCmpDocSeparator = { fg = p.border, bg = p.bg_float },
    BlinkCmpSignatureHelp = { fg = p.fg_ui, bg = p.bg_float },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg_float },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.type, bold = true },

    -- mini.* ----------------------------------------------------------------
    MiniIndentscopeSymbol = { fg = p.fg_gutter },
    MiniIndentscopePrefix = { nocombine = true },
    MiniSurround = { bg = p.bg_search_cur },
    MiniIconsAzure = { fg = p.blue },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.link },
    MiniIconsGreen = { fg = p.green },
    MiniIconsGrey = { fg = p.fg_dim },
    MiniIconsOrange = { fg = p.orange },
    MiniIconsPurple = { fg = p.purple },
    MiniIconsRed = { fg = p.red },
    MiniIconsYellow = { fg = p.yellow },

    -- lazy.nvim / mason -----------------------------------------------------
    LazyNormal = { fg = p.fg_ui, bg = p.bg_float },
    LazyButton = { fg = p.fg_ui, bg = p.bg_line },
    LazyButtonActive = { fg = p.on_accent, bg = p.accent_dim, bold = true },
    LazyH1 = { fg = p.on_accent, bg = p.accent_dim, bold = true },
    LazyH2 = { fg = p.fg_ui, bold = true },
    LazyReasonPlugin = { fg = p.func },
    LazyReasonEvent = { fg = p.type },
    LazyReasonKeys = { fg = p.link },
    LazyReasonStart = { fg = p.tag },
    LazyReasonSource = { fg = p.string },
    LazyReasonFt = { fg = p.constant },
    LazyReasonCmd = { fg = p.constant },
    LazyReasonImport = { fg = p.fg_ui },
    LazyReasonRequire = { fg = p.fg_dim },
    LazyProgressDone = { fg = p.ok, bold = true },
    LazyProgressTodo = { fg = p.fg_disabled, bold = true },
    LazyCommit = { fg = p.fg_dim },
    LazyDir = { fg = p.link },
    LazyUrl = { fg = p.link, underline = true },
    LazyProp = { fg = p.fg_dim },
    LazySpecial = { fg = p.accent },
    MasonNormal = { fg = p.fg_ui, bg = p.bg_float },
    MasonHeader = { fg = p.on_accent, bg = p.accent_dim, bold = true },
    MasonHeaderSecondary = { fg = p.fg_ui, bold = true },
    MasonHighlight = { fg = p.link },
    MasonHighlightBlock = { fg = p.on_accent, bg = p.accent_badge },
    MasonHighlightBlockBold = { fg = p.on_accent, bg = p.accent_badge, bold = true },
    MasonMuted = { fg = p.fg_disabled },
    MasonMutedBlock = { fg = p.fg_dim, bg = p.bg_line },

    -- grug-far --------------------------------------------------------------
    GrugFarHelpHeader = { fg = p.fg_ui, bold = true },
    GrugFarHelpHeaderKey = { fg = p.type },
    GrugFarHelpWinActionKey = { fg = p.type },
    GrugFarHelpWinActionText = { fg = p.fg_ui },
    GrugFarResultsHeader = { fg = p.link },
    GrugFarResultsPath = { fg = p.fg_ui, underline = true },
    GrugFarResultsLineNo = { fg = p.fg_gutter },
    GrugFarResultsMatch = { bg = p.bg_search },
    GrugFarResultsStats = { fg = p.fg_dim },

    -- render-markdown -------------------------------------------------------
    RenderMarkdownH1Bg = { fg = p.constant, bg = p.blend(p.constant, p.bg, 0.12) },
    RenderMarkdownH2Bg = { fg = p.constant, bg = p.blend(p.constant, p.bg, 0.1) },
    RenderMarkdownH3Bg = { fg = p.func, bg = p.blend(p.func, p.bg, 0.1) },
    RenderMarkdownH4Bg = { fg = p.func, bg = p.blend(p.func, p.bg, 0.08) },
    RenderMarkdownH5Bg = { fg = p.type, bg = p.blend(p.type, p.bg, 0.08) },
    RenderMarkdownH6Bg = { fg = p.type, bg = p.blend(p.type, p.bg, 0.06) },
    RenderMarkdownCode = { bg = p.bg_line }, -- textCodeBlock.background
    RenderMarkdownCodeInline = { fg = p.fg_dim, bg = "#262626" }, -- textPreformat.*
    RenderMarkdownBullet = { fg = p.keyword },
    RenderMarkdownQuote = { fg = p.fg_dim },
    RenderMarkdownDash = { fg = p.border },
    RenderMarkdownLink = { fg = p.link },
    RenderMarkdownTableHead = { fg = p.fg_ui },
    RenderMarkdownTableRow = { fg = p.fg_dim },
    RenderMarkdownSuccess = { fg = p.ok },
    RenderMarkdownInfo = { fg = p.info },
    RenderMarkdownHint = { fg = p.hint },
    RenderMarkdownWarn = { fg = p.warn },
    RenderMarkdownError = { fg = p.error },
    RenderMarkdownUnchecked = { fg = p.fg_dim },
    RenderMarkdownChecked = { fg = p.ok },

    -- copilot ---------------------------------------------------------------
    CopilotSuggestion = { fg = p.fg_disabled, italic = true },
    CopilotAnnotation = { fg = p.fg_disabled },
  }
end
