# Dark 2026
gui:
  theme:
    activeBorderColor:
      - "#3994bc"
      - bold
    inactiveBorderColor:
      - "#8c8c8c"
    optionsTextColor:
      - "#48a0c7"
    selectedLineBgColor:
      - "#276782"
