git:
  log:
    showWholeGraph: true
  overrideGpg: true

# Dark 2026
gui:
  theme:
    activeBorderColor:
      - "#3994bc"
      - bold
    inactiveBorderColor:
      - "#8c8c8c"
    optionsTextColor:
      - "#48a0c7"
    selectedLineBgColor:
      - "#276782"
    inactiveViewSelectedLineBgColor:
      - "#2c2d2e"
    cherryPickedCommitBgColor:
      - "#37373d"
    cherryPickedCommitFgColor:
      - "#e5ba7d"
    markedBaseCommitBgColor:
      - "#37373d"
    markedBaseCommitFgColor:
      - "#57a3f8"
    unstagedChangesColor:
      - "#f48771"
    defaultFgColor:
      - "#cccccc"
    searchingActiveBorderColor:
      - "#e5ba7d"

  authorColors:
    "*": "#57a3f8"
