git:
  log:
    showWholeGraph: true
# common
gui:
  theme:
    selectedLineBgColor:
      - "#6272a4"
# catppuccin mocha
# gui:
#   theme:
#     activeBorderColor:
#       - "#cba6f7"
#       - bold
#     inactiveBorderColor:
#       - "#a6adc8"
#     optionsTextColor:
#       - "#89b4fa"
#     selectedLineBgColor:
#       - "#313244"
#     cherryPickedCommitBgColor:
#       - "#45475a"
#     cherryPickedCommitFgColor:
#       - "#cba6f7"
#     unstagedChangesColor:
#       - "#f38ba8"
#     defaultFgColor:
#       - "#cdd6f4"
#     searchingActiveBorderColor:
#       - "#f9e2af"
#
#   authorColors:
#     "*": "#b4befe"
# catppuccin macchiato
# gui:
#   theme:
#     activeBorderColor:
#       - "#c6a0f6"
#       - bold
#     inactiveBorderColor:
#       - "#a5adcb"
#     optionsTextColor:
#       - "#8aadf4"
#     selectedLineBgColor:
#       - "#363a4f"
#     cherryPickedCommitBgColor:
#       - "#494d64"
#     cherryPickedCommitFgColor:
#       - "#c6a0f6"
#     unstagedChangesColor:
#       - "#ed8796"
#     defaultFgColor:
#       - "#cad3f5"
#     searchingActiveBorderColor:
#       - "#eed49f"
#
#   authorColors:
#     "*": "#b7bdf8"
# one dark pro
# gui:
#   theme:
#     activeBorderColor:
#       - "#61afef"
#       - bold
#     inactiveBorderColor:
#       - "#5c6370"
#     optionsTextColor:
#       - "#61afef"
#     selectedLineBgColor:
#       - "#3b4048"
#     cherryPickedCommitBgColor:
#       - "#30333d"
#     cherryPickedCommitFgColor:
#       - "#c678dd"
#     unstagedChangesColor:
#       - "#e06c75"
#     defaultFgColor:
#       - "#abb2bf"
#     searchingActiveBorderColor:
#       - "#e5c07b"
#
#   authorColors:
#     "*": "#98c379"
