# Catppuccin Mocha. LazyDocker supports these four theme colors.
gui:
  theme:
    activeBorderColor:
      - "#f9e2af"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
