# common
# gui:
#   theme:
#     selectedLineBgColor:
#       - "#6e6a86"
# edge dark
# gui:
#   theme:
#     selectedLineBgColor:
#       - "#424553"
# edge dark neon
# gui:
#   theme:
#     selectedLineBgColor:
#       - "#3f445b"
# catppuccin mocha
# gui:
#   theme:
#     activeBorderColor:
#       - "#f9e2af"
#       - bold
#     inactiveBorderColor:
#       - "#a6adc8"
#     optionsTextColor:
#       - "#89b4fa"
#     selectedLineBgColor:
#       - "#313244"
#     cherryPickedCommitBgColor:
#       - "#45475a"
#     cherryPickedCommitFgColor:
#       - "#f9e2af"
#     unstagedChangesColor:
#       - "#f38ba8"
#     defaultFgColor:
#       - "#cdd6f4"
#     searchingActiveBorderColor:
#       - "#f9e2af"
#
#   authorColors:
#     "*": "#b4befe"
# catppuccin macchiato
gui:
  theme:
    activeBorderColor:
      - "#eed49f"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#eed49f"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"

  authorColors:
    "*": "#b7bdf8"
